#! /bin/sh

# Colors
panel_bg='#1d1d1d'
panel_fg='#b3b4b1'

# Font

# Information

# Date
dateDMY() {
        date '+%d-%m-%y'
}

# Battery
battery() {
        BATC=/sys/class/power_supply/BAT0/capacity
        BATS=/sys/class/power_supply/BAT0/status
        
        test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'
        
        sed -n p $BATC
}

# Time
timeHR() {
        date '+%H:%M'
}

# WiFi
network() {
        wifi='iw wlan0 link'
        $wifi | grep SSID | awk '{print $2}'
        $wifi | grep signal | awk '{print $2}'
}

        

# Volume
volume() {
        amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+\)%.*$/\1/p'
}

# Memory
memory() {
        read t f <<< `grep -E 'Mem(Total|Free)' /proc/meminfo |awk '{print $2}'`
        bc <<< "scale=2; 100 - $f / $t * 100" | cut -d. -f1
}


while :; do
    buf=""
    buf="${buf} BAT:$(battery)"
    buf="${buf} DATE:$(dateDMY) "
    buf="${buf} NET:$(network)db  "
    buf="${buf} RAM:$(memory)%  "
    buf="${buf} VOL:$(volume)%"
    buf="${buf} TIME:$(timeHR)  "
    
    echo $buf
    sleep 2 
done
